### ISSUE TITLE
extract_locations.py fails to parse def from OpenROAD tools

### ISSUE THREAD

**Issue by tajayi** [The-OpenROAD-Project/TritonCTS#13]
TritonCTS (extract_locations.py) fails to properly parse the def file generated by openroad tools. The def file has the following syntax
```
COMPONENTS 262 ;
   - bb0 CELL_NAME
      + PLACED ( 168000 244000 ) FS ;
   - bb1 CELL_NAME
      + PLACED ( 159200 234400 ) FS ;
   - bb2 CELL_NAME
```
When I remove the extra lines things work

For reference, the one from innovus has the following syntax
```
COMPONENTS 349 ;
- ctrl/state/U3 CELL_NAME+ PLACED ( 48000 66400 ) N
 ;
- ctrl/state/out_reg_1_ CELL_NAME+ PLACED ( 124400 100000 ) FS
 ;
```

**Comment by mpfogaca** [comment]
Hi, Tutu.

Thanks -- We are aware of this problem. I'll commit a fix soon.

Thanks,
--Mateus

**Comment by tajayi** [comment]
Please let me know when this is fixed so I can remove our hacks
