### ISSUE TITLE
Update python calls in tritonCTS

### ISSUE THREAD

**Issue by tajayi** [The-OpenROAD-Project/TritonCTS#15]
We have run into a few scenarios where running TritonCTS fails across different machines and systems. 
Can you please make the following changes:
1. Update runTritonCTS.tcl to simply call the other python scripts directly (i.e ./scriptName.py"), instead of "python scriptName.py". The latter approach will use whatever python available on the system

2. Add a shebang to the top of the executable files "#! /usr/bin/env python3". This ensures the required python version is used. The files also have to be marked as an executable. 

**Note:** This is from issue https://github.com/The-OpenROAD-Project/alpha-release/issues/4 reported by @RTimothyEdwards in the alpha-release

**Comment by mpfogaca** [comment]
Hi, Tutu.

Can you try the fix?

Thanks,
--Mateus

**Comment by tajayi** [comment]
I believe this issue is resolved. Sorry for the delayed follow up
