### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by Roman-Parise** [The-OpenROAD-Project/TritonCTS#16]
[make.log](https://github.com/The-OpenROAD-Project/TritonCTS/files/3489233/make.log)

I have attached a log file. Basically, I run compileAll.sh with the proper arguments and receive build errors: "error: no member named 'X' in namespace 'Circuit'". I tried hacking away at it, but just made things worse. Has anyone else encountered these issues?

Default C Compiler: Clang 6.0.1
OS: FreeBSD 12.0

**Comment by mpfogaca** [comment]
@mgwoo: The problem seems to be in CtsHelper. Is there any easy workaround?

**Comment by Roman-Parise** [comment]
I raised the issue on the CtsHelper page. There doesn't seem to be an easy workaround, and it seems to fail for both gcc and Clang.

**Comment by mpfogaca** [comment]
Hi @Roman-Parise. 

Strange, we use gcc to compile in CentOS. We will remove the dependency of CtsHelper, but it will take some time. Meanwhile, could you use the images we provide with the alpha release?

https://github.com/The-OpenROAD-Project/alpha-release

Thanks,
--Mateus

**Comment by Roman-Parise** [comment]
Okay, so it actually works with the latest fix on the CtsHelper repo. However, now the issue is with the "git submodule update --init --recursive" line in compileAll.sh. When I manually update my CtsHelper submodule by setting its remote, pulling, and commenting out the "git submodule" line in compileAll.sh, it works like a charm. Otherwise, it updates CtsHelper with an older commit and breaks.

**Comment by mpfogaca** [comment]
Hi, @Roman-Parise -- 

The submodule also needed to be updated. Now it will work fine.

Thanks,
--Mateus

**Comment by mpfogaca** [comment]
Hi, @Roman-Parise --

Can you confirm the issue is solved?

Thanks,
--Mateus

**Comment by Roman-Parise** [comment]
Sorry about that. Just got a chance to check. The compileAll script built successfully on first pass for a clean clone. We're good.
