### ISSUE TITLE
Designs not completing due to "Too many solutions"

### ISSUE THREAD

**Issue by tajayi** [The-OpenROAD-Project/TritonCTS#18]
**Severity:** High

**Version:** commit e9815864ca5757e59927e9dd8af36694d9918871

**Details:**
The following designs are not able to complete due to issues in TritonCTS
- nangate45/swerv
- tsmc65lp/ariane
- tsmc65lp/swerv_wrapper

On further investigation, ghtree appears to fail with `Too many solutions, please try to increase the value of "toler" parameter`

**Steps to reproduce:**
1. Setup the latest version of the flow (commit e7abe2a8a010019f5a0c74472b96842cb66c2a71)
2. For tsmc65lp designs, obtain the private files are required. Contact me via email for details if you have access to the kit
3. Run either designs.

**Comment by mpfogaca** [comment]
Hi, Tutu.

Could you try again?

Thanks,
--Mateus

**Comment by tajayi** [comment]
Issue is resolved in all the designs. Thanks
