### ISSUE TITLE
New Process Setup - No feasible solution

### ISSUE THREAD

**Issue by yrrapt** [The-OpenROAD-Project/TritonCTS#23]
I'm trying to setup the OpenROAD environment for a different process from nand45 and I am running into an error in the CTS stage.  I can't appear to get past the GH-tree stage.  The debug information is presented below:

	*** Input parameters ***
	Area side: 12x12
	Max. skew: 50
	Max. latency: 2147483647
	#Leaf regions: 64
	Distance interval: 1
	Latency interval: 1
	Capacitance interval: 1
	Timing tolerance: 1000
	Tech node:  180
	Compute sink region mode 1
	Percentile 0.175
	
	TOTAL CAP = 180 fF
	
	 TritonCTS is running on 'computing sink region mode'
	 Computing sink region now...
	minx = 6.426
	miny = 6.50667
	maxx = 13.188
	maxy = 14.3147
	xoffset = 6.426
	yoffset = 6.50667
	width = 8
	height = 8
	Number of clock sinks: 180
	Number of sink regions: 64
	min_slew_idx: 0 out_slew_idx: 2
	***** Optimization *****
	Depth = 1 ..
	Depth = 2 ..
	13 solutions
	Depth = 3 ..
	4 solutions
	Depth = 4 ..
	0 solutions
	Depth = 5 ..
	0 solutions
	Depth = 6 ..
	0 solutions
	Depth = 7 ..
	0 solutions
	0 solutions
	Final n_dbg = 640
	No feasible solution
	child killed: segmentation violation

I have tried playing around with the input parameters to genHtree but it always fails.

Could this be due to an error in the characterisation files I generated?

I'm using a larger node (180 nm) than has been used for most of the testing, could it be that there's an issue in that?

Thanks in advance for any pointers you could give me.

**Comment by mpfogaca** [comment]
Hi, @yrrapt.

Yes, this looks like a problem in the characterization.

Could you paste here the first line of your .lut file? (Don't worry, the first line does not expose any technology information)

Separately, could you check if the values in your LUT are in the ballpark when compared to TritonCTS/src/tech/lut-45.txt ?

Thanks,
--Mateus

**Comment by yrrapt** [comment]
Hi @mpfogaca,

Apologies for the delay in responding.

The first line of my lut file is
`1 3 1 46 1 24`

Which is pretty close to the lut-45.txt file's first line of:
`1 4 1 34 1 16`

I will have another look at how I generated the characterisation files to see if there's anything I could have done wrong there.

Thanks

**Comment by yrrapt** [comment]
I have finally got around to giving this another go and have regenerated the characterisation files and now I can proceed past the TritonCTS stage.  So the issue was user error.
