### ISSUE TITLE
technology node variables hardcoded in runTritionCTS.tcl

### ISSUE THREAD

**Issue by kareefardi** [The-OpenROAD-Project/TritonCTS#24]
Hello. According to - https://github.com/The-OpenROAD-Project/TritonCTS/blob/291ded8ba9933b4e0cef4f032f3de82bbc82304e/runTritonCTS.tcl#L170

These variables: `buf_regex ck_pin buf_out_pin` are hardcoded for specific technology nodes. So running CTS for a different technology node terminates the script.

Edit:
Perhaps these variables should be added as configuration parameters.

**Comment by maliberty** [comment]
obsolete
